services:
  mysql:
    build:
      context: "./docker/mysql/"
      args:
        MARIADB_VERSION: ${MARIADB_VERSION}
        MARIADB_IMAGE: ${MARIADB_IMAGE}
    command: --sql_mode="NO_ENGINE_SUBSTITUTION,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/:/root/sql
      - ./docker/mysql/settings.cnf:/etc/mysql/conf.d/settings.cnf
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: "Europe/Amsterdam"
  mailcatcher:
    image: 'schickling/mailcatcher'
    ports:
      - "1080:1080"

  php:
    build:
      context: './docker/php'
      dockerfile: Dockerfile
      args:
        TIMEZONE: "Europe/Berlin"
    volumes:
      - './:/var/www:delegated'
    depends_on:
      - mysql
    environment:
      - COMPOSER_MEMORY_LIMIT=-1
  apache:
    build:
      context: './docker/apache/'
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - "./:/var/www:delegated"
    depends_on:
      - php
      - mysql
      - mailcatcher

volumes:
  mysql_data: